### ISSUE TITLE
Types are not published on npm

### ISSUE THREAD

**Issue by jozsefsallai** [octet-stream/dinky#11]
Hello!

I noticed that the repo contains type declarations, however, they are not published on npm yet (they were created after March, when the latest release was published). This makes it a bit cumbersome to work with dinky.js in a TypeScript environment (right now I'm using patch-package to add the missing types or I just pull the package from Github).

Is there any reason why the latest changes weren't published since March? And when do you think you could make the type declarations available in the package too?

No rush, just a question :)

**Comment by octet-stream** [comment]
I was thinking to add tests for these typings first, but turns out I have no much time to support this project.
I can just publish them anyways.

**Comment by jozsefsallai** [comment]
I just tried building the project (using `tsc` instead of `ts-node`) and it fails to build with this error:

```
node_modules/dinky.js/lib/Dinky.d.ts:47:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

47 class Dinky {
   ~~~~~
```

**Comment by octet-stream** [comment]
Is it happening when you're trying the lib with typings (directly from github repo) or is it on the latest version from NPM?

**Comment by octet-stream** [comment]
I'm asking because i'm not familiar with TS, I'm ok using JS so I don't see any reason to learn it.
~~Except that VSCode autocompletions and lack of them when I'm using `prop-types` in my react projects makes me feel like I write types with JSDoc anyway :D~~

**Comment by jozsefsallai** [comment]
Directly from the github repo haha
When I open the d.ts file in vscode it also highlights this issue (and some more after patching it).

**Comment by octet-stream** [comment]
I don't know, I don't see any problem in VSCode.

**Comment by jozsefsallai** [comment]
It's missing a `declare` in front of the following:
- `class Dinky`
- `function dinky`
- `class NetworkError`
- `namespace responses`

if you want, I can open a quick PR since I already patched the file in my project anyway.

**Comment by octet-stream** [comment]
But according to the error's description this might have something with the way how types are exported from the .d.ts module. Not sure if they force to do export at the same line when the type was declared.

**Comment by octet-stream** [comment]
> if you want, I can open a quick PR since I already patched the file in my project anyway.

Sure, if it will fix that.

@Veetaha hey 👋 Don't you remember if you had same issue when you fixed the exports after I asked you to do so?

**Comment by Veetaha** [comment]
I don't remember having this issue, but now it makes sense, `declare` should be enough to fix

**Comment by octet-stream** [comment]
Ok then, Now I have to publish it :D

**Comment by octet-stream** [comment]
Done. You can try https://github.com/octet-stream/dinky/releases/tag/v.1.1.0 now.

**Comment by jozsefsallai** [comment]
Thank you, works like a charm :)
